name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'  # Use a versão desejada do Node.js

      - name: Prepare and Deploy to S3
        run: |
          cd service-report-front
          npm install
          npm run build
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          aws s3 sync dist/ ${{ secrets.BUCKET_NAME }}