name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'  # Use a versão desejada do Node.js

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIARQI3K76CSSMJQ3XN
          aws-secret-access-key: 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
          aws-region: sa-east-1

      - name: Prepare and Deploy to S3
        run: |
          cd service-report-front
          npm install
          npm run build